// Mocks generated by Mockito 5.4.6 from annotations
// in park_wallet/test/unit/controllers/profile_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:get/get.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:park_wallet/data/dto/user_profile_update_request.dart' as _i8;
import 'package:park_wallet/data/models/user_profile.dart' as _i3;
import 'package:park_wallet/repositories/profile_repository.dart' as _i6;
import 'package:park_wallet/services/auth_service.dart' as _i2;
import 'package:park_wallet/services/profile_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i4.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileService_3 extends _i1.SmartFake
    implements _i5.ProfileService {
  _FakeProfileService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i6.ProfileRepository {
  @override
  _i2.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_0(
              this,
              Invocation.getter(#authService),
            ),
            returnValueForMissingStub: _FakeAuthService_0(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i2.AuthService);

  @override
  set authService(_i2.AuthService? _authService) => super.noSuchMethod(
    Invocation.setter(#authService, _authService),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i3.UserProfile> fetchUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, []),
            returnValue: _i7.Future<_i3.UserProfile>.value(
              _FakeUserProfile_1(
                this,
                Invocation.method(#fetchUserProfile, []),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.UserProfile>.value(
              _FakeUserProfile_1(
                this,
                Invocation.method(#fetchUserProfile, []),
              ),
            ),
          )
          as _i7.Future<_i3.UserProfile>);

  @override
  _i7.Future<void> updateUserProfile(_i8.UserProfileUpdateRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [request]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i5.ProfileService {
  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<_i5.ProfileService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<_i5.ProfileService>.value(
              _FakeProfileService_3(this, Invocation.method(#init, [])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.ProfileService>.value(
              _FakeProfileService_3(this, Invocation.method(#init, [])),
            ),
          )
          as _i7.Future<_i5.ProfileService>);

  @override
  void clearProfile() => super.noSuchMethod(
    Invocation.method(#clearProfile, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> refreshProfile() =>
      (super.noSuchMethod(
            Invocation.method(#refreshProfile, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
